java_library(
    name = "failureaccess",
    exports = [
        "//external:jar/com/google/guava/failureaccess"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)



java_library(
    name = "guava",
    exports = [
        "//dependencies/maven/artifacts/com/google/j2objc:j2objc-annotations",
        "//dependencies/maven/artifacts/org/checkerframework:checker-compat-qual",
        "//external:jar/com/google/guava/guava",
        ":failureaccess",
        ":listenablefuture"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)



java_library(
    name = "listenablefuture",
    exports = [
        "//external:jar/com/google/guava/listenablefuture"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


