java_library(
    name = "fastparse-2-12",
    exports = [
        "//external:jar/com/lihaoyi/fastparse-2-12",
        ":sourcecode-2-12"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)



java_library(
    name = "sourcecode-2-12",
    exports = [
        "//dependencies/maven/artifacts/org/scala-lang:scala-library",
        "//external:jar/com/lihaoyi/sourcecode-2-12"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


