java_library(
    name = "scala-library",
    exports = [
        "//external:jar/org/scala-lang/scala-library"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


